"""add reference to tasktemplate model

Revision ID: 1540b1d104b1
Revises: 974911c4058d
Create Date: 2025-11-18 12:39:17.325031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1540b1d104b1'
down_revision: Union[str, Sequence[str], None] = '974911c4058d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_templates', sa.Column('reference', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_templates', 'reference')
    # ### end Alembic commands ###
