"""add Aircraft Airline Aircraft type

Revision ID: d07a5da44500
Revises: 087c38960964
Create Date: 2025-08-03 14:27:19.879028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd07a5da44500'
down_revision: Union[str, Sequence[str], None] = '087c38960964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aircraft_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airline', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_type_id', sa.Integer(), nullable=False),
    sa.Column('registration_no', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_type_id'], ['aircraft_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['airline_id'], ['airlines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aircraft')
    op.drop_table('airlines')
    op.drop_table('aircraft_types')
    # ### end Alembic commands ###
